Import

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import make_column_transformer

Data Prep

In [2]:
essays = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/essays.csv')
outcomes = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/outcomes.csv')
projects = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/projects.csv')
resources = pd.read_csv('kdd-cup-2014-predicting-excitement-at-donors-choose/data/resources.csv')

In [3]:
#get length of project description

essays['short_description'] = essays['short_description'].astype(str)
essays['essay'] = essays['essay'].astype(str)
essays['short_description_length'] = essays['short_description'].apply(len)
essays['essay_length'] = essays['essay'].apply(len)

#make project outcome binary

to_binary = {'f':0,'t':1}
outcomes['fully_funded'] = outcomes['fully_funded'].map(to_binary)

In [11]:
project_outcomes = projects.merge(outcomes,how='inner',on='projectid')
essay_outcomes = essays.merge(outcomes,how='inner',on='projectid')

In [12]:
project_outcomes.isna().sum()

projectid                                              0
teacher_acctid                                         0
schoolid                                               0
school_ncesid                                      38848
school_latitude                                        0
school_longitude                                       0
school_city                                            0
school_state                                           0
school_zip                                             4
school_metro                                       75488
school_district                                      922
school_county                                         17
school_charter                                         0
school_magnet                                          0
school_year_round                                      0
school_nlns                                            0
school_kipp                                            0
school_charter_ready_promise                           0
teacher_prefix                                         0
teacher_teach_for_america                              0
teacher_ny_teaching_fellow                             0
primary_focus_subject                                 36
primary_focus_area                                    36
secondary_focus_subject                           193949
secondary_focus_area                              193949
resource_type                                         43
poverty_level                                          0
grade_level                                            7
fulfillment_labor_materials                        35082
total_price_excluding_optional_support                 0
total_price_including_optional_support                 0
students_reached                                     144
eligible_double_your_impact_match                      0
eligible_almost_home_match                             0
date_posted                                            0
is_exciting                                            0
at_least_1_teacher_referred_donor                  94398
fully_funded                                           0
at_least_1_green_donation                          94398
great_chat                                             0
three_or_more_non_teacher_referred_donors          94398
one_non_teacher_referred_donor_giving_100_plus     94398
donation_from_thoughtful_donor                     94398
great_messages_proportion                         179839
teacher_referred_count                             94398
non_teacher_referred_count                         94398
dtype: int64

In [ ]:
project_outcomes.groupby('school_state')['fully_funded'].mean().sort_values(ascending=False)

In [13]:
project_outcomes.groupby('primary_focus_subject')['fully_funded'].mean().sort_values(ascending=False)

primary_focus_subject
Nutrition                0.794326
Environmental Science    0.777787
Economics                0.766756
Music                    0.760829
Health & Life Science    0.747439
Sports                   0.738298
Performing Arts          0.729484
Visual Arts              0.729011
Applied Sciences         0.720853
Civics & Government      0.712999
Character Education      0.699716
History & Geography      0.697184
Health & Wellness        0.697046
Mathematics              0.695781
Community Service        0.691810
Social Sciences          0.690321
Literacy                 0.686502
Special Needs            0.679731
Literature & Writing     0.677855
Extracurricular          0.677564
Foreign Languages        0.665429
College & Career Prep    0.662970
ESL                      0.660615
Gym & Fitness            0.660555
Early Development        0.640826
Parent Involvement       0.598192
Other                    0.578355
Name: fully_funded, dtype: float64

In [ ]:
project_outcomes.groupby('school_metro')['fully_funded'].mean().sort_values(ascending=False)

school_metro
urban       0.736195
suburban    0.675168
rural       0.603399
Name: fully_funded, dtype: float64

In [17]:
project_outcomes.groupby('poverty_level')['fully_funded'].mean().sort_values(ascending=False)

poverty_level
highest poverty     0.726354
low poverty         0.669308
high poverty        0.658163
moderate poverty    0.639796
Name: fully_funded, dtype: float64

In [18]:
project_outcomes.groupby('resource_type')['fully_funded'].mean().sort_values(ascending=False)

resource_type
Books         0.762421
Trips         0.738100
Supplies      0.730294
Other         0.687430
Visitors      0.669231
Technology    0.614816
Name: fully_funded, dtype: float64

In [19]:
project_outcomes.groupby('grade_level')['fully_funded'].mean().sort_values(ascending=False)

grade_level
Grades 9-12      0.717418
Grades PreK-2    0.695475
Grades 6-8       0.691063
Grades 3-5       0.687040
Name: fully_funded, dtype: float64

In [25]:
project_outcomes['school_charter'].value_counts()

school_charter
f    565942
t     53384
Name: count, dtype: int64

In [26]:
project_outcomes.groupby('school_charter')['fully_funded'].mean().sort_values(ascending=False)

school_charter
t    0.743462
f    0.690873
Name: fully_funded, dtype: float64

In [24]:
project_outcomes['school_nlns'].value_counts()

school_nlns
f    609738
t      9588
Name: count, dtype: int64

In [21]:
project_outcomes.groupby('school_nlns')['fully_funded'].mean().sort_values(ascending=False)

school_nlns
t    0.787338
f    0.693960
Name: fully_funded, dtype: float64

In [27]:
project_outcomes['school_kipp'].value_counts()

school_kipp
f    615132
t      4194
Name: count, dtype: int64

In [28]:
project_outcomes.groupby('school_kipp')['fully_funded'].mean().sort_values(ascending=False)

school_kipp
t    0.798283
f    0.694705
Name: fully_funded, dtype: float64

In [29]:
project_outcomes['school_magnet'].value_counts()

school_magnet
f    560811
t     58515
Name: count, dtype: int64

In [30]:
project_outcomes.groupby('school_magnet')['fully_funded'].mean().sort_values(ascending=False)

school_magnet
t    0.721952
f    0.692636
Name: fully_funded, dtype: float64

In [31]:
project_outcomes['eligible_double_your_impact_match'].value_counts()

eligible_double_your_impact_match
f    448003
t    171323
Name: count, dtype: int64

In [32]:
project_outcomes.groupby('eligible_double_your_impact_match')['fully_funded'].mean().sort_values(ascending=False)

eligible_double_your_impact_match
t    0.767737
f    0.667746
Name: fully_funded, dtype: float64

In [37]:
project_outcomes['eligible_almost_home_match'].value_counts()

eligible_almost_home_match
f    581870
t     37456
Name: count, dtype: int64

In [38]:
project_outcomes.groupby('eligible_almost_home_match')['fully_funded'].mean().sort_values(ascending=False)

eligible_almost_home_match
t    0.796481
f    0.688900
Name: fully_funded, dtype: float64

In [33]:
project_outcomes['teacher_teach_for_america'].value_counts()

teacher_teach_for_america
f    583241
t     36085
Name: count, dtype: int64

In [34]:
project_outcomes.groupby('teacher_teach_for_america')['fully_funded'].mean().sort_values(ascending=False)

teacher_teach_for_america
t    0.824442
f    0.687423
Name: fully_funded, dtype: float64

In [35]:
project_outcomes['teacher_ny_teaching_fellow'].value_counts()

teacher_ny_teaching_fellow
f    608255
t     11071
Name: count, dtype: int64

In [36]:
project_outcomes.groupby('teacher_ny_teaching_fellow')['fully_funded'].mean().sort_values(ascending=False)

teacher_ny_teaching_fellow
t    0.807515
f    0.693365
Name: fully_funded, dtype: float64

Feature Matrix 1

In [6]:
df = project_outcomes[['projectid','school_state',"school_metro","fully_funded",'poverty_level']]

In [34]:
df = df[df['school_state'] != 'La']
df.dropna()

,projectid,school_state,school_metro,fully_funded,poverty_level
0,62526d85d2a1818432d03d600969e99c,IL,suburban,1,moderate poverty
1,33d59ac771b80222ad63ef0f4ac47ade,ID,urban,0,high poverty
2,1a3aaeffc56dd2a421e37d8298024c0a,NH,suburban,0,moderate poverty
3,33aa19ee4da4c5adf47d0dfb84fab5ef,VA,urban,0,highest poverty
4,e31c0ea8b68f404699dfb0d39e9bc99b,IL,urban,1,highest poverty
...,...,...,...,...,...
619320,1c8fe14031d38a86d43f7dd09955279b,NY,urban,1,highest poverty
619321,a7236ea96c812895cafc5d700d779147,NY,urban,1,highest poverty
619322,e02da37beb332eb66c2d2ba989c597ad,NY,urban,1,highest poverty
619323,82e536f14eadf2671a70e03416f695a3,NY,urban,1,moderate poverty
619325,77558a6eda151deee9a00553f7fccfc7,NY,urban,1,highest poverty

In [35]:
ohe = OneHotEncoder(sparse_output=False)
ct = make_column_transformer(
       (ohe, ['school_state','school_metro','poverty_level']),
       remainder = 'passthrough'
)

In [36]:
matrix = ct.fit_transform(df)
matrix[:5, : ]

array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        '62526d85d2a1818432d03d600969e99c', 1],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        '33d59ac771b80222ad63ef0f4ac47ade', 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        '1a3aaeffc56dd2a421e37d8298024c0a', 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        '33aa19ee4da4c5adf47d0dfb84fab5ef', 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        'e31c0ea8b68f404699dfb0d39e9bc99b', 1]], dtype=object)

Feature Matrix 2

In [10]:
df2 = project_outcomes[['projectid','total_price_excluding_optional_support','students_reached','fully_funded']]

In [11]:
q1 = df2['total_price_excluding_optional_support'].quantile(0.25)
q3 = df2['total_price_excluding_optional_support'].quantile(0.75)
iqr = q1 - q3

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [12]:
df2_iqr = df2[(df2['total_price_excluding_optional_support'] >= lower_bound)]
df2_iqr = df2[(df2['total_price_excluding_optional_support'] <= upper_bound)]

In [24]:
df2_iqr.groupby('fully_funded').describe()

#question: which iqr do we take if we have two features with outliers?

             total_price_excluding_optional_support                        \
                                              count       mean        std
fully_funded
0                                             332.0  24.876566  41.976876
1                                            3122.0  91.354798  24.095077

                                                students_reached             \
              min    25%     50%    75%     max            count       mean
fully_funded
0             0.0   0.00    0.00   36.9  110.24            332.0  20.216867
1             0.0  85.08  101.03  106.6  110.29           3122.0  54.302691


                     std  min   25%   50%   75%     max
fully_funded
0              67.283330  0.0   0.0   0.0  20.0   600.0
1             112.994017  0.0  18.0  24.0  40.0  2250.0

In [14]:
df2_iqr

,projectid,total_price_excluding_optional_support,students_reached,fully_funded
7192,f38bc08e8be6bea9c94bca6495153728,89.38,30.0,1
11071,b994c82a07627606f20d47ea40bfde85,101.05,24.0,1
11604,1523f15a6cf149112dbf8d177c8ed642,101.05,26.0,1
14056,4317c29216f030b7121538cc13bb9fac,101.05,22.0,1
18261,695dd9b6d52c3345032ecf0bbe7f13a2,101.05,24.0,1
...,...,...,...,...
619266,11646fe7b97e08354cde2246c5e582c1,9.00,0.0,1
619273,9527bb30da568d09785f6a418c791a5f,54.00,0.0,1
619274,7758a201bf8c9a41b919dfe53505f71b,0.00,0.0,0
619287,ca17cdf71b5bf6e74f20792f8d5230ef,68.00,0.0,1
619313,00cb0cf6fc2d8bc03493d88a6a453e92,83.00,0.0,1

Feature Matrix 3

In [23]:
df3 = essay_outcomes[['projectid','short_description_length','essay_length','fully_funded']]
df3

,projectid,short_description_length,essay_length,fully_funded
0,ffffc4f85b60efc5b52347df489d0238,273,2615,0
1,ffffac55ee02a49d1abc87ba6fc61135,195,1155,1
2,ffff97ed93720407d70a2787475932b0,270,1327,1
3,ffff418bb42fad24347527ad96100f81,270,1081,0
4,ffff2d9c769c8fb5335e949c615425eb,199,2799,1
...,...,...,...,...
619321,0000ee613c92ddc5298bf63142996a5c,199,2375,1
619322,0000b38bbc7252972f7984848cf58098,190,2036,1
619323,00002d691c05c51a5fdfbb2baef0ba25,275,1273,0
619324,00002bff514104264a6b798356fdd893,273,1698,1
619325,00001ccc0e81598c4bd86bacb94d7acb,197,1453,1

Feature Matrix 4

In [28]:
df4 = project_outcomes[['projectid','grade_level','primary_focus_subject','resource_type','fully_funded']]

In [29]:
ohe = OneHotEncoder(sparse_output=False)
ct = make_column_transformer(
       (ohe, ['grade_level','primary_focus_subject','resource_type']),
       remainder = 'passthrough'
)

In [30]:
matrix2 = ct.fit_transform(df4)
matrix2[:5, : ]

array([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, '62526d85d2a1818432d03d600969e99c', 1],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, '33d59ac771b80222ad63ef0f4ac47ade', 0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, '1a3aaeffc56dd2a421e37d8298024c0a', 0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, '33aa19ee4da4c5adf47d0dfb84fab5ef', 0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 'e31c0ea8b68f404699dfb0d39e9bc99b', 1]], dtype=object)